In [3]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

#### squeeze() : 차원중 1인 것을 제거

In [4]:
ft=torch.FloatTensor([[0], [1], [2]])

In [6]:
ft.squeeze()

tensor([0., 1., 2.])

In [7]:
ft=torch.FloatTensor([[[0], [1], [2]]])

In [8]:
ft

tensor([[[0.],
         [1.],
         [2.]]])

In [9]:
ft.squeeze()

tensor([0., 1., 2.])

#### Unsqueeze() : 특정 위치에 1인 차원 추가

In [10]:
ft=torch.FloatTensor([1,2,3])

In [11]:
ft.unsqueeze(0)

tensor([[1., 2., 3.]])

In [12]:
ft.unsqueeze(1)

tensor([[1.],
        [2.],
        [3.]])

#### Concatenate and stack

In [13]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])
torch.cat([x,y], dim=0)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [14]:
torch.cat([x,y], dim=1)

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])

In [16]:
torch.stack([x,y])

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])

In [20]:
xx = torch.FloatTensor([0,1])
yy = torch.FloatTensor([2,3])
zz = torch.FloatTensor([4,5])

In [21]:
torch.stack([xx,yy, zz], dim=0)

tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])

In [22]:
torch.stack([xx,yy, zz], dim=1)

tensor([[0., 2., 4.],
        [1., 3., 5.]])

In [23]:
torch.cat([xx,yy, zz], dim=0)

tensor([0., 1., 2., 3., 4., 5.])

#### ones_like and zeros_like

In [27]:
torch.ones_like(xx)

tensor([1., 1.])

In [28]:
torch.zeros_like(yy)

tensor([0., 0.])

#### In-place operation

In [29]:
x1=torch.FloatTensor([[0.,1.], [2., 3.]])

In [34]:
x1.mul(2)

tensor([[ 0.,  8.],
        [16., 24.]])

In [33]:
x1.mul_(2) # in-place operation

tensor([[ 0.,  4.],
        [ 8., 12.]])

In [32]:
x1

tensor([[0., 2.],
        [4., 6.]])